version: '3.8'

services:
  vaccination-mysql:
    image: mysql
    container_name: vaccination-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - mynet
    environment:
      - MYSQL_USER=${SQL_USER}
      - MYSQL_PASSWORD=${SQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${SQL_PASSWORD}
      - MYSQL_DATABASE=${SQL_DBNAME}
    ports:
      - 3306:3306
    volumes:
      - vaccination-db:/var/lib/mysql

volumes:
  vaccination-db:

networks:
  mynet:
    driver: bridge
